## Titanic_Survival_Predictor

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset("titanic")

In [3]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [6]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [7]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
categorical_cols

Index(['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive'], dtype='object')

In [8]:
for i in categorical_cols:
  print(f"the value count of {i} : ")
  print(df[i].value_counts(),"/n")

the value count of sex : 
sex
male      577
female    314
Name: count, dtype: int64 /n
the value count of embarked : 
embarked
S    644
C    168
Q     77
Name: count, dtype: int64 /n
the value count of class : 
class
Third     491
First     216
Second    184
Name: count, dtype: int64 /n
the value count of who : 
who
man      537
woman    271
child     83
Name: count, dtype: int64 /n
the value count of deck : 
deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64 /n
the value count of embark_town : 
embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64 /n
the value count of alive : 
alive
no     549
yes    342
Name: count, dtype: int64 /n


In [9]:
df['age'].fillna(df['age'].mean(), inplace=True)
df.dropna(subset=['embarked'],inplace=True)


In [10]:
for i in categorical_cols:
  print(f"the value count of {i} : ")
  print(df[i].value_counts(),"/n")

the value count of sex : 
sex
male      577
female    312
Name: count, dtype: int64 /n
the value count of embarked : 
embarked
S    644
C    168
Q     77
Name: count, dtype: int64 /n
the value count of class : 
class
Third     491
First     214
Second    184
Name: count, dtype: int64 /n
the value count of who : 
who
man      537
woman    269
child     83
Name: count, dtype: int64 /n
the value count of deck : 
deck
C    59
B    45
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64 /n
the value count of embark_town : 
embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64 /n
the value count of alive : 
alive
no     549
yes    340
Name: count, dtype: int64 /n


In [11]:
df.drop( ['class', 'who', 'deck', 'embark_town', 'alive'],axis=1,inplace=True)


In [12]:
df_encode=pd.get_dummies(df,drop_first=True)
df_encode

survived  pclass        age  sibsp  parch     fare  adult_male  alone  \
0           0       3  22.000000      1      0   7.2500        True  False   
1           1       1  38.000000      1      0  71.2833       False  False   
2           1       3  26.000000      0      0   7.9250       False   True   
3           1       1  35.000000      1      0  53.1000       False  False   
4           0       3  35.000000      0      0   8.0500        True   True   
..        ...     ...        ...    ...    ...      ...         ...    ...   
886         0       2  27.000000      0      0  13.0000        True   True   
887         1       1  19.000000      0      0  30.0000       False   True   
888         0       3  29.699118      1      2  23.4500       False  False   
889         1       1  26.000000      0      0  30.0000        True   True   
890         0       3  32.000000      0      0   7.7500        True   True   

     sex_male  embarked_Q  embarked_S  
0        True       False        True  
1       False       False       False  
2       False       False        True  
3       False       False        True  
4        True       False        True  
..        ...         ...         ...  
886      True       False        True  
887     False       False        True  
888     False       False        True  
889      True       False       False  
890      True        True       False  

[889 rows x 11 columns]

In [13]:
df_encode = df_encode.astype(int)
df_encode

survived  pclass  age  sibsp  parch  fare  adult_male  alone  sex_male  \
0           0       3   22      1      0     7           1      0         1   
1           1       1   38      1      0    71           0      0         0   
2           1       3   26      0      0     7           0      1         0   
3           1       1   35      1      0    53           0      0         0   
4           0       3   35      0      0     8           1      1         1   
..        ...     ...  ...    ...    ...   ...         ...    ...       ...   
886         0       2   27      0      0    13           1      1         1   
887         1       1   19      0      0    30           0      1         0   
888         0       3   29      1      2    23           0      0         0   
889         1       1   26      0      0    30           1      1         1   
890         0       3   32      0      0     7           1      1         1   

     embarked_Q  embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[889 rows x 11 columns]

In [14]:
df['pclass'].value_counts()

pclass
3    491
1    214
2    184
Name: count, dtype: int64

In [15]:
df_encode.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    889 non-null    int64
 1   pclass      889 non-null    int64
 2   age         889 non-null    int64
 3   sibsp       889 non-null    int64
 4   parch       889 non-null    int64
 5   fare        889 non-null    int64
 6   adult_male  889 non-null    int64
 7   alone       889 non-null    int64
 8   sex_male    889 non-null    int64
 9   embarked_Q  889 non-null    int64
 10  embarked_S  889 non-null    int64
dtypes: int64(11)
memory usage: 83.3 KB


In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df_scaled=pd.DataFrame(scaler.fit_transform(df_encode),columns=df_encode.columns)
df_scaled

survived    pclass       age     sibsp     parch      fare  adult_male  \
0   -0.786961  0.825209 -0.578023  0.431350 -0.474326 -0.496733    0.809626   
1    1.270711 -1.572211  0.655371  0.431350 -0.474326  0.791539   -1.235139   
2    1.270711  0.825209 -0.269675 -0.475199 -0.474326 -0.496733   -1.235139   
3    1.270711 -1.572211  0.424109  0.431350 -0.474326  0.429213   -1.235139   
4   -0.786961  0.825209  0.424109 -0.475199 -0.474326 -0.476604    0.809626   
..        ...       ...       ...       ...       ...       ...         ...   
884 -0.786961 -0.373501 -0.192588 -0.475199 -0.474326 -0.375957    0.809626   
885  1.270711 -1.572211 -0.809285 -0.475199 -0.474326 -0.033760   -1.235139   
886 -0.786961  0.825209 -0.038413  0.431350  2.006119 -0.174665   -1.235139   
887  1.270711 -1.572211 -0.269675 -0.475199 -0.474326 -0.033760    0.809626   
888 -0.786961  0.825209  0.192848 -0.475199 -0.474326 -0.496733    0.809626   

        alone  sex_male  embarked_Q  embarked_S  
0   -1.229349  0.735342   -0.307941    0.616794  
1   -1.229349 -1.359911   -0.307941   -1.621287  
2    0.813439 -1.359911   -0.307941    0.616794  
3   -1.229349 -1.359911   -0.307941    0.616794  
4    0.813439  0.735342   -0.307941    0.616794  
..        ...       ...         ...         ...  
884  0.813439  0.735342   -0.307941    0.616794  
885  0.813439 -1.359911   -0.307941    0.616794  
886 -1.229349 -1.359911   -0.307941    0.616794  
887  0.813439  0.735342   -0.307941   -1.621287  
888  0.813439  0.735342    3.247377   -1.621287  

[889 rows x 11 columns]

In [17]:
X=df_scaled.drop('survived',axis=1)
y=df['survived']

## Logistic regression Model

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [19]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)


LogisticRegression()

In [20]:
y_pred=model.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [21]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_pred)

0.8146067415730337

In [23]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [14, 55]])

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85       109
           1       0.74      0.80      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.81      0.82       178



## K-nearest Neighbours Model

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train,y_train)


KNeighborsClassifier()

In [26]:
knn_pred=knn_model.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,knn_pred)

0.7865168539325843

In [28]:
print(classification_report(y_test,knn_pred))

              precision    recall  f1-score   support

           0       0.84      0.81      0.82       109
           1       0.71      0.75      0.73        69

    accuracy                           0.79       178
   macro avg       0.78      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178



## Naive Baye's Model

In [29]:
from sklearn.naive_bayes import GaussianNB
model_nb=GaussianNB()
model_nb.fit(X_train,y_train)

GaussianNB()

In [30]:
nb_pred=model_nb.predict(X_test)

In [31]:
accuracy_score(y_test,nb_pred)

0.8089887640449438

In [32]:
print(classification_report(y_test,nb_pred))

              precision    recall  f1-score   support

           0       0.87      0.81      0.84       109
           1       0.73      0.81      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.80       178
weighted avg       0.82      0.81      0.81       178



## Decision Tree Model

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
dtc_model=DecisionTreeClassifier(random_state=42)
dtc_model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [35]:
dtc_pred=dtc_model.predict(X_test)
dtc_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [36]:
accuracy_score(dtc_pred,y_test)

0.7865168539325843

In [37]:
print(classification_report(dtc_pred,y_test))

              precision    recall  f1-score   support

           0       0.79      0.85      0.82       101
           1       0.78      0.70      0.74        77

    accuracy                           0.79       178
   macro avg       0.79      0.78      0.78       178
weighted avg       0.79      0.79      0.78       178



## Support Vector Machine Model

In [38]:
from sklearn.svm import SVC

In [39]:
svm_model=SVC(kernel ='rbf')
svm_model.fit(X_train,y_train)

SVC()

In [40]:
svm_pred=svm_model.predict(X_test)


In [41]:
accuracy_score(svm_pred,y_test)

0.8202247191011236

In [42]:
print(confusion_matrix(svm_pred,y_pred))

[[104   5]
 [  0  69]]


In [43]:
print(classification_report(svm_pred,y_test))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       109
           1       0.77      0.77      0.77        69

    accuracy                           0.82       178
   macro avg       0.81      0.81      0.81       178
weighted avg       0.82      0.82      0.82       178

